"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from Service.webhook_api import WebhookApi  # noqa: E501


class TestWebhookApi(unittest.TestCase):
    """WebhookApi unit test stubs"""

    def setUp(self):
        self.api = WebhookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_dynamic_webhook(self):
        """Test case for post_dynamic_webhook

        Dynamic Webhook  # noqa: E501
        """
        pass

    def test_post_static_webhook(self):
        """Test case for post_static_webhook

        Static Webhook  # noqa: E501
        """
        pass

    def test_replicate_dynamic_webhook(self):
        """Test case for replicate_dynamic_webhook

        Replicate Dynamic Webhook  # noqa: E501
        """
        pass

    def test_replicate_static_webhook(self):
        """Test case for replicate_static_webhook

        Replicate Static Webhook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
