"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.23
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import event_manager_client
from event_manager_client.model.source_job_request import SourceJobRequest


class TestSourceJobRequest(unittest.TestCase):
    """SourceJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceJobRequest(self):
        """Test SourceJobRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SourceJobRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
