"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from Service.aggregate_api import AggregateApi  # noqa: E501


class TestAggregateApi(unittest.TestCase):
    """AggregateApi unit test stubs"""

    def setUp(self):
        self.api = AggregateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aggregate_events(self):
        """Test case for get_aggregate_events

        Aggregate all events from a specific job  # noqa: E501
        """
        pass

    def test_replicate_child_aggregate_event(self):
        """Test case for replicate_child_aggregate_event

        Replicate Child Aggregate Event  # noqa: E501
        """
        pass

    def test_replicate_parent_aggregate_event(self):
        """Test case for replicate_parent_aggregate_event

        Replicate a Parent Aggregate event  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
