"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from Service.key_api import KeyApi  # noqa: E501


class TestKeyApi(unittest.TestCase):
    """KeyApi unit test stubs"""

    def setUp(self):
        self.api = KeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_key(self):
        """Test case for get_key

        Fetch key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
