"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.full_api_key import FullApiKey


class TestFullApiKey(unittest.TestCase):
    """FullApiKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFullApiKey(self):
        """Test FullApiKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FullApiKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
