"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from Service.job_api import JobApi  # noqa: E501


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_job(self):
        """Test case for create_job

        Create a new job  # noqa: E501
        """
        pass

    def test_create_job_schedule(self):
        """Test case for create_job_schedule

        Create a job schedule  # noqa: E501
        """
        pass

    def test_delete_job(self):
        """Test case for delete_job

        Delete jobs  # noqa: E501
        """
        pass

    def test_get_job_by_id(self):
        """Test case for get_job_by_id

        Get a job by job id  # noqa: E501
        """
        pass

    def test_get_jobs_by(self):
        """Test case for get_jobs_by

        Get a list of jobs by  # noqa: E501
        """
        pass

    def test_replicate_job(self):
        """Test case for replicate_job

        Replicate job  # noqa: E501
        """
        pass

    def test_update_job(self):
        """Test case for update_job

        Update job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
