"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from Service.organisation_api import OrganisationApi  # noqa: E501


class TestOrganisationApi(unittest.TestCase):
    """OrganisationApi unit test stubs"""

    def setUp(self):
        self.api = OrganisationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_organisation_index(self):
        """Test case for create_organisation_index

        Create the organisation tables  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
