"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from Service.event_entity_api import EventEntityApi  # noqa: E501


class TestEventEntityApi(unittest.TestCase):
    """EventEntityApi unit test stubs"""

    def setUp(self):
        self.api = EventEntityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_event_entity(self):
        """Test case for update_event_entity

        Update Event Entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
