"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_job_request import UpdateJobRequest


class TestUpdateJobRequest(unittest.TestCase):
    """UpdateJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateJobRequest(self):
        """Test UpdateJobRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateJobRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
