"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.schedule_configuration_request import ScheduleConfigurationRequest


class TestScheduleConfigurationRequest(unittest.TestCase):
    """ScheduleConfigurationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduleConfigurationRequest(self):
        """Test ScheduleConfigurationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScheduleConfigurationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
