"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payload_in_list import PayloadInList
globals()['PayloadInList'] = PayloadInList
from openapi_client.model.replicate_job_request import ReplicateJobRequest


class TestReplicateJobRequest(unittest.TestCase):
    """ReplicateJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReplicateJobRequest(self):
        """Test ReplicateJobRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReplicateJobRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
