"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from Service.api_key_api import ApiKeyApi  # noqa: E501


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self):
        self.api = ApiKeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_api_key(self):
        """Test case for create_api_key

        Create a new API key  # noqa: E501
        """
        pass

    def test_delete_api_key(self):
        """Test case for delete_api_key

        Delete an API key  # noqa: E501
        """
        pass

    def test_get_all_api_keys_by_organisation(self):
        """Test case for get_all_api_keys_by_organisation

        Fetch all API keys associated with an Organisation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
