"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.event import Event
globals()['Event'] = Event
from openapi_client.model.event_list import EventList


class TestEventList(unittest.TestCase):
    """EventList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventList(self):
        """Test EventList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
