"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from Service.stream_api import StreamApi  # noqa: E501


class TestStreamApi(unittest.TestCase):
    """StreamApi unit test stubs"""

    def setUp(self):
        self.api = StreamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_schedule_configuration(self):
        """Test case for create_schedule_configuration

        Create a new Stream Schedule Configuration  # noqa: E501
        """
        pass

    def test_delete_schedule_configuration(self):
        """Test case for delete_schedule_configuration

        Delete a Stream Schedule Configuration  # noqa: E501
        """
        pass

    def test_get_schedule_configuration(self):
        """Test case for get_schedule_configuration

        Get a Stream Schedule Configuration by Stream Id  # noqa: E501
        """
        pass

    def test_update_schedule_configuration_attributes(self):
        """Test case for update_schedule_configuration_attributes

        Updates Stream Schedule Configuration option and active attributes.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
