"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.23
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from event_manager_client.api_client import ApiClient, Endpoint as _Endpoint
from event_manager_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from event_manager_client.model.async_response import AsyncResponse
from event_manager_client.model.replicate_event_request import ReplicateEventRequest
from event_manager_client.model.replicate_parent_aggregate_event_request import ReplicateParentAggregateEventRequest


class AggregateApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __get_aggregate_events(
            self,
            organisation_id,
            stream_id,
            job_id,
            **kwargs
        ):
            """Aggregate all events from a specific job  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_aggregate_events(organisation_id, stream_id, job_id, async_req=True)
            >>> result = thread.get()

            Args:
                organisation_id (str):
                stream_id (str):
                job_id (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                AsyncResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['organisation_id'] = \
                organisation_id
            kwargs['stream_id'] = \
                stream_id
            kwargs['job_id'] = \
                job_id
            return self.call_with_http_info(**kwargs)

        self.get_aggregate_events = _Endpoint(
            settings={
                'response_type': (AsyncResponse,),
                'auth': [
                    'admin_apikey'
                ],
                'endpoint_path': '/event_manager/aggregate_events/{organisation_id}/{stream_id}/{job_id}',
                'operation_id': 'get_aggregate_events',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'organisation_id',
                    'stream_id',
                    'job_id',
                ],
                'required': [
                    'organisation_id',
                    'stream_id',
                    'job_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'organisation_id':
                        (str,),
                    'stream_id':
                        (str,),
                    'job_id':
                        (str,),
                },
                'attribute_map': {
                    'organisation_id': 'organisation_id',
                    'stream_id': 'stream_id',
                    'job_id': 'job_id',
                },
                'location_map': {
                    'organisation_id': 'path',
                    'stream_id': 'path',
                    'job_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_aggregate_events
        )

        def __replicate_child_aggregate_event(
            self,
            **kwargs
        ):
            """Replicate Child Aggregate Event  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.replicate_child_aggregate_event(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                organisation_id (str): [optional]
                replicate_event_request (ReplicateEventRequest): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                AsyncResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.replicate_child_aggregate_event = _Endpoint(
            settings={
                'response_type': (AsyncResponse,),
                'auth': [
                    'apikey'
                ],
                'endpoint_path': '/event_manager/aggregate_events/replicate_child',
                'operation_id': 'replicate_child_aggregate_event',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'organisation_id',
                    'replicate_event_request',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'organisation_id':
                        (str,),
                    'replicate_event_request':
                        (ReplicateEventRequest,),
                },
                'attribute_map': {
                    'organisation_id': 'organisation-id',
                },
                'location_map': {
                    'organisation_id': 'header',
                    'replicate_event_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__replicate_child_aggregate_event
        )

        def __replicate_parent_aggregate_event(
            self,
            replicate_parent_aggregate_event_request,
            **kwargs
        ):
            """Replicate a Parent Aggregate event  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.replicate_parent_aggregate_event(replicate_parent_aggregate_event_request, async_req=True)
            >>> result = thread.get()

            Args:
                replicate_parent_aggregate_event_request (ReplicateParentAggregateEventRequest): Event Data

            Keyword Args:
                organisation_id (str): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                AsyncResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['replicate_parent_aggregate_event_request'] = \
                replicate_parent_aggregate_event_request
            return self.call_with_http_info(**kwargs)

        self.replicate_parent_aggregate_event = _Endpoint(
            settings={
                'response_type': (AsyncResponse,),
                'auth': [
                    'admin_apikey'
                ],
                'endpoint_path': '/event_manager/aggregate_events/replicate_parent',
                'operation_id': 'replicate_parent_aggregate_event',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'replicate_parent_aggregate_event_request',
                    'organisation_id',
                ],
                'required': [
                    'replicate_parent_aggregate_event_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'replicate_parent_aggregate_event_request':
                        (ReplicateParentAggregateEventRequest,),
                    'organisation_id':
                        (str,),
                },
                'attribute_map': {
                    'organisation_id': 'organisation-id',
                },
                'location_map': {
                    'replicate_parent_aggregate_event_request': 'body',
                    'organisation_id': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__replicate_parent_aggregate_event
        )
