# flake8: noqa

"""
    HighCohesion API

    HighCohesion API [https://highcohesion.co.uk](https://highcohesion.co.uk)   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Contact: admin@highcohesion.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.21"

# import ApiClient
from event_manager_client.api_client import ApiClient

# import Configuration
from event_manager_client.configuration import Configuration

# import exceptions
from event_manager_client.exceptions import OpenApiException
from event_manager_client.exceptions import ApiAttributeError
from event_manager_client.exceptions import ApiTypeError
from event_manager_client.exceptions import ApiValueError
from event_manager_client.exceptions import ApiKeyError
from event_manager_client.exceptions import ApiException
